# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sam_segmentation_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# 修复：添加 Qt 常量导入（关键）
from PyQt5.QtCore import Qt


class Ui_SamSegmentationDialogBase(object):
    def setupUi(self, SamSegmentationDialogBase):
        SamSegmentationDialogBase.setObjectName("SamSegmentationDialogBase")
        SamSegmentationDialogBase.resize(900, 750)  # 扩大窗口尺寸适配两页布局
        
        # 主布局：顶部切换按钮 + 堆叠窗口 + 日志 + 底部按钮
        main_layout = QtWidgets.QVBoxLayout(SamSegmentationDialogBase)
        main_layout.setObjectName("mainLayout")
        
        # 1. 页面切换按钮区（顶部）
        self.switch_buttons_layout = QtWidgets.QHBoxLayout()
        self.switch_buttons_layout.setObjectName("switch_buttons_layout")
        
        self.btn_switch_to_params = QtWidgets.QPushButton("参数设置")
        self.btn_switch_to_params.setObjectName("btn_switch_to_params")
        self.switch_buttons_layout.addWidget(self.btn_switch_to_params)
        
        self.btn_switch_to_function = QtWidgets.QPushButton("返回功能页")
        self.btn_switch_to_function.setObjectName("btn_switch_to_function")
        self.switch_buttons_layout.addWidget(self.btn_switch_to_function)
        
        main_layout.addLayout(self.switch_buttons_layout)
        
        # 2. 堆叠窗口（核心：包含两个页面）
        self.stacked_widget = QtWidgets.QStackedWidget()
        self.stacked_widget.setObjectName("stacked_widget")
        
        # ------------------------------
        # 第一页：模型功能页（原核心功能）
        # ------------------------------
        self.page_function = QtWidgets.QWidget()
        self.page_function.setObjectName("page_function")
        self.function_layout = QtWidgets.QVBoxLayout(self.page_function)
        
        # 图层选择
        self.layer_group = QtWidgets.QGroupBox("图层配置")
        self.layer_layout = QtWidgets.QHBoxLayout(self.layer_group)
        self.layer_layout.addWidget(QtWidgets.QLabel("选择栅格图层："))
        self.layerCombo = QtWidgets.QComboBox()
        self.layerCombo.setObjectName("layerCombo")
        self.layer_layout.addWidget(self.layerCombo)
        self.function_layout.addWidget(self.layer_group)
        
        # 模型配置（SAM2配置文件+模型文件+模型类型）
        self.model_config_group = QtWidgets.QGroupBox("模型配置")
        self.model_config_layout = QtWidgets.QGridLayout(self.model_config_group)
        
        # SAM2配置文件
        self.model_config_layout.addWidget(QtWidgets.QLabel("SAM2配置文件："), 0, 0)
        self.configPathValue = QtWidgets.QLabel("未选择")
        self.model_config_layout.addWidget(self.configPathValue, 0, 1)
        self.browseConfigBtn = QtWidgets.QPushButton("浏览")
        self.model_config_layout.addWidget(self.browseConfigBtn, 0, 2)
        
        # 模型文件
        self.model_config_layout.addWidget(QtWidgets.QLabel("模型权重文件："), 1, 0)
        self.modelPathValue = QtWidgets.QLabel("未选择")
        self.model_config_layout.addWidget(self.modelPathValue, 1, 1)
        self.browseModelBtn = QtWidgets.QPushButton("浏览")
        self.model_config_layout.addWidget(self.browseModelBtn, 1, 2)
        
        # 模型类型
        self.model_config_layout.addWidget(QtWidgets.QLabel("模型类型："), 2, 0)
        self.modelTypeCombo = QtWidgets.QComboBox()
        self.modelTypeCombo.addItems(["vit_h", "vit_l", "vit_b"])
        self.model_config_layout.addWidget(self.modelTypeCombo, 2, 1)
        self.loadModelBtn = QtWidgets.QPushButton("加载模型")
        self.model_config_layout.addWidget(self.loadModelBtn, 2, 2)
        
        self.function_layout.addWidget(self.model_config_group)
        
        # 采样尺寸控制
        self.sample_size_group = QtWidgets.QGroupBox("处理尺寸配置")
        self.sample_size_layout = QtWidgets.QHBoxLayout(self.sample_size_group)
        self.sampleSizeLabel = QtWidgets.QLabel("最大处理尺寸：2000px")
        # 修复：此处使用 Qt.Horizontal 需要导入 Qt 模块
        self.sampleSizeSlider = QtWidgets.QSlider(Qt.Horizontal)
        self.sampleSizeSlider.setMinimum(500)
        self.sampleSizeSlider.setMaximum(4000)
        self.sampleSizeSlider.setValue(2000)
        self.sampleSizeSlider.setTickInterval(500)
        self.sample_size_layout.addWidget(self.sampleSizeLabel)
        self.sample_size_layout.addWidget(self.sampleSizeSlider)
        self.function_layout.addWidget(self.sample_size_group)
        
        # 核心操作按钮
        self.operation_group = QtWidgets.QGroupBox("标注操作")
        self.operation_layout = QtWidgets.QHBoxLayout(self.operation_group)
        self.foregroundBtn = QtWidgets.QPushButton("前景标注")
        self.backgroundBtn = QtWidgets.QPushButton("背景标注")
        self.undoBtn = QtWidgets.QPushButton("撤销")
        self.clearBtn = QtWidgets.QPushButton("清除所有")
        self.saveShpBtn = QtWidgets.QPushButton("保存Shapefile")
        self.operation_layout.addWidget(self.foregroundBtn)
        self.operation_layout.addWidget(self.backgroundBtn)
        self.operation_layout.addWidget(self.undoBtn)
        self.operation_layout.addWidget(self.clearBtn)
        self.operation_layout.addWidget(self.saveShpBtn)
        self.function_layout.addWidget(self.operation_group)
        
        # 功能页占位（填充空白）
        self.function_layout.addStretch()
        
        # 添加功能页到堆叠窗口
        self.stacked_widget.addWidget(self.page_function)
        
        # ------------------------------
        # 第二页：参数设置页
        # ------------------------------
        self.page_params = QtWidgets.QWidget()
        self.page_params.setObjectName("page_params")
        self.params_layout = QtWidgets.QVBoxLayout(self.page_params)
        
        # 分割参数面板
        self.segment_group = QtWidgets.QGroupBox("SAM2 分割参数")
        self.segment_layout = QtWidgets.QFormLayout(self.segment_group)
        self.params_layout.addWidget(self.segment_group)
        
        # Mask处理参数面板
        self.mask_group = QtWidgets.QGroupBox("Mask 处理参数")
        self.mask_layout = QtWidgets.QFormLayout(self.mask_group)
        self.params_layout.addWidget(self.mask_group)
        
        # 矢量转换参数面板
        self.vector_group = QtWidgets.QGroupBox("矢量转换参数")
        self.vector_layout = QtWidgets.QFormLayout(self.vector_group)
        self.params_layout.addWidget(self.vector_group)
        
        # 参数页占位
        self.params_layout.addStretch()
        
        # 添加参数页到堆叠窗口
        self.stacked_widget.addWidget(self.page_params)
        
        # 将堆叠窗口添加到主布局
        main_layout.addWidget(self.stacked_widget)
        
        # 3. 日志控件
        self.log_group = QtWidgets.QGroupBox("操作日志")
        self.log_layout = QtWidgets.QVBoxLayout(self.log_group)
        self.logText = QtWidgets.QTextEdit()
        self.logText.setReadOnly(True)
        self.log_layout.addWidget(self.logText)
        main_layout.addWidget(self.log_group)
        
        # 4. 底部按钮（关闭）
        self.buttonBox = QtWidgets.QDialogButtonBox()
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        main_layout.addWidget(self.buttonBox)
        
        # 信号连接（基础）
        self.buttonBox.rejected.connect(SamSegmentationDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(SamSegmentationDialogBase)
        
        # 初始化页面（默认显示功能页）
        self.stacked_widget.setCurrentWidget(self.page_function)

    def retranslateUi(self, SamSegmentationDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SamSegmentationDialogBase.setWindowTitle(_translate("SamSegmentationDialogBase", "SAM2 交互式分割插件"))
        self.layer_group.setTitle(_translate("SamSegmentationDialogBase", "图层配置"))
        self.model_config_group.setTitle(_translate("SamSegmentationDialogBase", "模型配置"))
        self.sample_size_group.setTitle(_translate("SamSegmentationDialogBase", "处理尺寸配置"))
        self.operation_group.setTitle(_translate("SamSegmentationDialogBase", "标注操作"))
        self.segment_group.setTitle(_translate("SamSegmentationDialogBase", "SAM2 分割参数"))
        self.mask_group.setTitle(_translate("SamSegmentationDialogBase", "Mask 处理参数"))
        self.vector_group.setTitle(_translate("SamSegmentationDialogBase", "矢量转换参数"))
        self.log_group.setTitle(_translate("SamSegmentationDialogBase", "操作日志"))
        self.btn_switch_to_params.setText(_translate("SamSegmentationDialogBase", "参数设置"))
        self.btn_switch_to_function.setText(_translate("SamSegmentationDialogBase", "返回功能页"))
        self.foregroundBtn.setText(_translate("SamSegmentationDialogBase", "前景标注"))
        self.backgroundBtn.setText(_translate("SamSegmentationDialogBase", "背景标注"))
        self.undoBtn.setText(_translate("SamSegmentationDialogBase", "撤销"))
        self.clearBtn.setText(_translate("SamSegmentationDialogBase", "清除所有"))
        self.saveShpBtn.setText(_translate("SamSegmentationDialogBase", "保存Shapefile"))
        self.loadModelBtn.setText(_translate("SamSegmentationDialogBase", "加载模型"))
        self.browseConfigBtn.setText(_translate("SamSegmentationDialogBase", "浏览"))
        self.browseModelBtn.setText(_translate("SamSegmentationDialogBase", "浏览"))